# Java Gradle CircleCI 2.0 Configuration file.
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Grant access to ./gradlew.
          command: |
           chmod +x gradlew

      - run:
          name: Show the Gradle version in use with other details.
          command: |
           ./gradlew --version

      - run:
          name: Set up the workspace for ci build
          command: |
           ./gradlew setupCiWorkspace

      - run:
          name: Clean the workspace ready for a fresh build.
          command: |
           ./gradlew clean

      - run:
          name: Attempt to build the mod.
          command: |
           ./gradlew build

      - store_artifacts:
          path: ./build/libs
